url: "https://great7media.github.io"
baseurl: ""

# Site settings
title: "great7media의 포트폴리오"
subtitle: Portfolio
email: great7media@gmail.com
description: "기획, 시나리오 작성부터 편집까지, 차별화된 영상 제작을 약속드립니다. great7media의 웹 포트폴리오입니다."

# Postal address (add as many lines as necessary)
address:
  - line: Seoul, Republic of Korea

# Build settings
markdown: kramdown
permalink: /:categories/:title
#permalink: pretty

# Reading Files
exclude:
  - .git
  - .gitattributes
  - .gitignore
  - .jekyll-cache
  - LICENSE
  - README
  - "*.sh"
